import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { CheckCircle2, XCircle, TrendingUp, Award, BookOpen, Target, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import LearningResourcesDialog from "./LearningResourcesDialog";

interface SkillAnalysisProps {
  data: {
    matchScore: number;
    matchedSkills: string[];
    missingSkills: string[];
    recommendedSkills: string[];
    experienceScore: number;
    educationScore: number;
  } | null;
}

const SkillAnalysis = ({ data }: SkillAnalysisProps) => {
  const [showResources, setShowResources] = useState(false);
  const { toast } = useToast();

  if (!data) {
    return (
      <div className="py-12 text-center">
        <p className="text-muted-foreground">No analysis data available</p>
      </div>
    );
  }

  const handleExportReport = () => {
    // Generate report content
    const reportContent = `
SKILL MATCH ANALYSIS REPORT
===========================

Overall Match Score: ${data.matchScore}%
Experience Score: ${data.experienceScore}%
Education Score: ${data.educationScore}%

MATCHED SKILLS (${data.matchedSkills.length}):
${data.matchedSkills.map((skill) => `✓ ${skill}`).join("\n")}

MISSING SKILLS (${data.missingSkills.length}):
${data.missingSkills.map((skill) => `✗ ${skill}`).join("\n")}

RECOMMENDED SKILLS TO LEARN (${data.recommendedSkills.length}):
${data.recommendedSkills.map((skill, index) => `${index + 1}. ${skill}`).join("\n")}

---
Generated by SkillMatch AI
${new Date().toLocaleDateString()}
    `.trim();

    // Create and download the file
    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `skill-analysis-report-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    toast({
      title: "Report exported!",
      description: "Your skill analysis report has been downloaded.",
    });
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-success";
    if (score >= 60) return "text-warning";
    return "text-destructive";
  };

  const getScoreGradient = (score: number) => {
    if (score >= 80) return "from-success to-success/70";
    if (score >= 60) return "from-warning to-warning/70";
    return "from-destructive to-destructive/70";
  };

  return (
    <div className="space-y-6">
      {/* Overall Match Score */}
      <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-accent/5 p-8">
        <div className="mb-6 text-center">
          <div className="mb-3 inline-flex items-center gap-2 rounded-full bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
            <Target className="h-4 w-4" />
            Overall Match Score
          </div>
          <div className={`mb-2 text-6xl font-bold ${getScoreColor(data.matchScore)}`}>
            {data.matchScore}%
          </div>
          <p className="text-muted-foreground">
            {data.matchScore >= 80
              ? "Excellent match! You're well-qualified for this position."
              : data.matchScore >= 60
              ? "Good match! Consider developing a few more skills."
              : "Moderate match. Focus on building the required skills."}
          </p>
        </div>
        <Progress 
          value={data.matchScore} 
          className="h-3"
        />
      </Card>

      {/* Detailed Scores */}
      <div className="grid gap-4 md:grid-cols-2">
        <Card className="border-accent/20 bg-card p-6">
          <div className="mb-4 flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10">
              <Award className="h-5 w-5 text-accent" />
            </div>
            <div>
              <p className="font-semibold">Experience Match</p>
              <p className="text-sm text-muted-foreground">Based on your background</p>
            </div>
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-2xl font-bold">{data.experienceScore}%</span>
            </div>
            <Progress value={data.experienceScore} className="h-2" />
          </div>
        </Card>

        <Card className="border-success/20 bg-card p-6">
          <div className="mb-4 flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-success/10">
              <BookOpen className="h-5 w-5 text-success" />
            </div>
            <div>
              <p className="font-semibold">Education Match</p>
              <p className="text-sm text-muted-foreground">Qualification alignment</p>
            </div>
          </div>
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-2xl font-bold">{data.educationScore}%</span>
            </div>
            <Progress value={data.educationScore} className="h-2" />
          </div>
        </Card>
      </div>

      {/* Matched Skills */}
      <Card className="border-success/20 bg-card p-6">
        <div className="mb-4 flex items-center gap-2">
          <CheckCircle2 className="h-5 w-5 text-success" />
          <h3 className="text-xl font-semibold">Matched Skills</h3>
          <Badge variant="secondary" className="ml-auto">
            {data.matchedSkills.length} skills
          </Badge>
        </div>
        <div className="flex flex-wrap gap-2">
          {data.matchedSkills.map((skill) => (
            <Badge
              key={skill}
              className="bg-success/10 text-success hover:bg-success/20"
            >
              {skill}
            </Badge>
          ))}
        </div>
      </Card>

      {/* Missing Skills */}
      <Card className="border-destructive/20 bg-card p-6">
        <div className="mb-4 flex items-center gap-2">
          <XCircle className="h-5 w-5 text-destructive" />
          <h3 className="text-xl font-semibold">Skills Gap</h3>
          <Badge variant="secondary" className="ml-auto">
            {data.missingSkills.length} skills
          </Badge>
        </div>
        <p className="mb-4 text-sm text-muted-foreground">
          These skills are required but not found in your resume
        </p>
        <div className="flex flex-wrap gap-2">
          {data.missingSkills.map((skill) => (
            <Badge
              key={skill}
              variant="outline"
              className="border-destructive/30 text-destructive"
            >
              {skill}
            </Badge>
          ))}
        </div>
      </Card>

      {/* Recommended Skills */}
      <Card className="border-primary/20 bg-gradient-to-br from-primary/5 to-accent/5 p-6">
        <div className="mb-4 flex items-center gap-2">
          <TrendingUp className="h-5 w-5 text-primary" />
          <h3 className="text-xl font-semibold">Recommended to Learn</h3>
        </div>
        <p className="mb-4 text-sm text-muted-foreground">
          Prioritize learning these skills to improve your match and career prospects
        </p>
        <div className="mb-6 flex flex-wrap gap-2">
          {data.recommendedSkills.map((skill) => (
            <Badge
              key={skill}
              className="bg-gradient-to-r from-primary to-accent text-white"
            >
              {skill}
            </Badge>
          ))}
        </div>
        <div className="flex gap-3">
          <Button variant="outline" className="flex-1 gap-2" onClick={handleExportReport}>
            <Download className="h-4 w-4" />
            Export Report
          </Button>
          <Button className="flex-1 gap-2" onClick={() => setShowResources(true)}>
            <BookOpen className="h-4 w-4" />
            Find Learning Resources
          </Button>
        </div>
      </Card>

      <LearningResourcesDialog
        open={showResources}
        onOpenChange={setShowResources}
        skills={data.recommendedSkills}
      />
    </div>
  );
};

export default SkillAnalysis;
